# Generated by Django 2.2.10 on 2020-10-29 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20201027_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='high_priority_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='low_priority_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='medium_priority_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
