# Generated by Django 2.2.10 on 2020-10-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20201029_0710'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriorityHigh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PriorityLow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PriorityMedium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='todoitem',
            name='high_priority_count',
        ),
        migrations.RemoveField(
            model_name='todoitem',
            name='low_priority_count',
        ),
        migrations.RemoveField(
            model_name='todoitem',
            name='medium_priority_count',
        ),
    ]
